name: integration-test.yml
permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: "Set environment"
        run: cp .env_example .env
      - name: "Set preseed"
        run: echo "PRESEED=true" >> $GITHUB_ENV
      - name: "Start service"
        run: docker compose -f docker-compose.yml up -d --wait
      - name: "Test server"
        run: docker exec -it service-a-1 yarn test