name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm i
        working-directory: frontend
      - run: npm run lint
        working-directory: frontend
      - run: npm run prettier -- --check
        working-directory: frontend
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - run: npm i
        working-directory: backend
      - run: npm run lint
        working-directory: backend
      - run: npm run prettier -- --check
        working-directory: backend
      - run: npm exec redocly lint ../dist/openapi.json
        working-directory: backend
